<?php
/**
 * Application,模块及分发控制器
 * @package cloud.core.components
 * @author oShine <oshine.ouyang@da-mai.com>
 */

namespace cloud\core\web;

use cloud\Cloud;
use cloud\core\engines\Engine;
use cloud\core\utils\Module;
use Yii;
use yii\helpers\ArrayHelper;

class Application extends \yii\web\Application {

    /**
     * 已安装的模块
     * @var array 
     */
    private $_enabledModule = array();

    /**
     * @param array $config
     * @throws \yii\base\InvalidConfigException
     */
    public function preInit(&$config) {

        $engineClass = 'cloud\core\engines\\' . ( ucfirst( strtolower( ENGINE ) ) );
        /**
         * @var Engine $engine
         */
        $engine = new $engineClass();
        Cloud::setEngine( $engine );

        $config = ArrayHelper::merge($config,$engine->getConfig());

        $this->_enabledModule = Module::fetchAllModule();
        foreach ($this->_enabledModule as $name => $mc) {

            if (isset($mc['config'])) {
                $config = ArrayHelper::merge($config,$mc['config']);
            }
        }

        parent::preInit($config);
    }


    public function bootstrap()
    {
        $this->on(self::EVENT_BEFORE_REQUEST,['cloud\core\web\InitEnv','handle']);

        $engine = Cloud::engine();
        $engine->bootstrap();

        $this->bootstrap = array_merge($this->bootstrap,['cache','log']);
        parent::bootstrap(); // TODO: Change the autogenerated stub
    }

    /**
     * 返回可用的模块数组
     * @return array
     */
    public function getEnabledModule() {
        return (array) $this->_enabledModule;
    }

    /**
     * @inheritdoc
     */
    public function coreComponents()
    {
        return array_merge(parent::coreComponents(), [
            'log' => [
              'targets' => [
                  'file' => [
                      'class' => 'yii\log\FileTarget',
                      'levels' => ['error'],
                      'categories' => ['*'],
                      'logFile'=>'@runtime/logs/webapp.'.date("Y-m-d").".log"

                  ],
                ],
            ],
            'assetManager' => [
                'class' => 'yii\web\AssetManager',
                'basePath' => '@webroot/static',
                'baseUrl' => '@web/static'
            ],
            'browser' => ['class' => 'cloud\core\components\Browser'],
            'setting' => ['class' => 'cloud\core\components\Setting'],
            'cache' => ['class'=>'yii\caching\FileCache']
        ]);
    }

}
