<?php

namespace cloud\core\modules;

class Module extends \yii\base\Module {

	public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (\Yii::$app instanceof \yii\console\Application) {
            $this->controllerNamespace = 'app\modules\\'.$this->id.'\cli';
        }
    }
}
