<?php
/**
 * @author oshine <oyjqdlp@126.com>
 * @link https://github.com/ouyangjunqiu/ou.cloud
 * @see https://github.com/ouyangjunqiu/ou.cloud
 */
namespace cloud\core\modules;

class Module extends \yii\base\Module {

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (\Yii::$app instanceof \yii\console\Application || \Yii::$app instanceof cloud\core\cli\Application) {
            $this->controllerNamespace = 'app\modules\\'.$this->id.'\cli';
        }
        $this->registerTranslations();
    }


    public function registerTranslations()
    {
        \Yii::$app->i18n->translations['modules/'.$this->id.'/*'] = [
            'class' => 'yii\i18n\PhpMessageSource',
            'sourceLanguage' => \Yii::$app->language,
            'basePath' => '@app/modules/'.$this->id.'/messages',
            'fileMap' => [
            ],
        ];
    }


}
